spring:
  application:
    name: fighthub

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

# LOG Configuration
logging:
  level:
    root: INFO
    dev.kellyson.fighthub: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

  structured:
    format:
      console: ecs